[XComGame.X2SoldierClass_DefaultClasses]

+SoldierClasses=PC_Chryssalid_Class

[PC_Chryssalid_Class X2SoldierClassTemplate]
+bMultiplayerOnly=0
+ClassPoints=3
+IconImage="img:///UILibrary_XPACK_Common.class_alien"
+NumInForcedDeck=0
+NumInDeck=0
+KillAssistsPerKill=5
+bCanHaveBonds=true 
+bAllowAWCAbilities=1
+UnfavoredClasses="PC_Chryssalid_Class"
+BaseAbilityPointsPerPromotion=4
+bIgnoreInjuries=1
+bNoSecondaryWeapon=true
+SquaddieLoadout="PC_Chryssalid_Loadout"
+RequiredCharacterClass="PC_Chryssalid"
+AllowedArmors="chryssalid_armor"
+AllowedWeapons=(SlotType=eInvSlot_PrimaryWeapon, WeaponType="chryssalid_melee")
+CannotEditSlots=eInvSlot_Utility


+ExcludedAbilities="Infiltration"
+ExcludedAbilities="Judgment"
+ExcludedAbilities="SkirmisherReflex"
+ExcludedAbilities="LightningReflexes"
+ExcludedAbilities="Shadowstrike"
+ExcludedAbilities="RunAndGun"
+ExcludedAbilities="HoloTargeting"
+ExcludedAbilities="Implacable"
+ExcludedAbilities="DeepCover"
+ExcludedAbilities="Untouchable"
+ExcludedAbilities="CoveringFire"
+ExcludedAbilities="BloodTrail"
+ExcludedAbilities="SkirmisherReturnFire"
+ExcludedAbilities="EverVigilant"
+ExcludedAbilities="SoulReaper"
+ExcludedAbilities="BulletShred"

; Squaddie Rank (Rank 0) - Give it the standard Chryssalid attack
+SoldierRanks=(  AbilitySlots=( (AbilityType=(AbilityName="PC_ChryssalidSlash")) ), \\
                aStatProgression=( (StatType=eStat_Offense, StatAmount=0) ) \\
             )